// generated by stringer -type IndexType; DO NOT EDIT

package reflector

import "fmt"

const _IndexType_name = "startIndexIndexBtreeIndexFulltextIndexHashIndexRtreestopIndex"

var _IndexType_index = [...]uint8{0, 10, 20, 33, 42, 52, 61}

func (i IndexType) String() string {
	if i < 0 || i+1 >= IndexType(len(_IndexType_index)) {
		return fmt.Sprintf("IndexType(%d)", i)
	}
	return _IndexType_name[_IndexType_index[i]:_IndexType_index[i+1]]
}
