// generated by stringer -type SQLType; DO NOT EDIT

package reflector

import "fmt"

const _SQLType_name = "startSQLTypeSQLStringSQLBytesSQLIntegerSQLFloatSQLBoolSQLTimestopSQLType"

var _SQLType_index = [...]uint8{0, 12, 21, 29, 39, 47, 54, 61, 72}

func (i SQLType) String() string {
	if i < 0 || i+1 >= SQLType(len(_SQLType_index)) {
		return fmt.Sprintf("SQLType(%d)", i)
	}
	return _SQLType_name[_SQLType_index[i]:_SQLType_index[i+1]]
}
